name: atom2024

channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - plotly=5.15.0
  - rdkit=2023.03.2
  - numpy=1.25.1
  - pip
  - pip: 
    - tiktoken==0.4.0
    - pre-commit==3.3.3
